from __future__ import annotations

from typing import Any, Protocol

from .schemas import CreateActivityEventRequestDto, CreateTaskRequestDto, MoveTaskRequestDto, UpdateTaskRequestDto, UpdateWorkflowNodeRequestDto


class Repository(Protocol):
    loaded: bool

    def list_tasks(self) -> list[dict[str, Any]]: ...
    def create_task(self, request: CreateTaskRequestDto) -> dict[str, Any]: ...
    def update_task(self, task_id: str, request: UpdateTaskRequestDto) -> dict[str, Any]: ...
    def move_task(self, task_id: str, request: MoveTaskRequestDto) -> dict[str, Any]: ...
    def list_activity_events(self) -> list[dict[str, Any]]: ...
    def create_activity_event(self, request: CreateActivityEventRequestDto) -> dict[str, Any]: ...
    def list_workflow_nodes(self) -> list[dict[str, Any]]: ...
    def list_workflow_edges(self) -> list[dict[str, Any]]: ...
    def update_workflow_node(self, node_id: str, request: UpdateWorkflowNodeRequestDto) -> dict[str, Any]: ...
    def validate_workflow(self) -> dict[str, Any]: ...
    def simulate_workflow(self) -> dict[str, Any]: ...
    def publish_workflow(self) -> dict[str, Any]: ...
